version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
environment:
  HIDRIVE_CLIENT_ID:
    secure: GE1BL08v0stKESuBTeL6uy4XCxBXfU429d3hpMnmbX5uNTDjTVVzEmh4tKXki1Mz
  HIDRIVE_CLIENT_SECRET:
    secure: oxnOCbKjrBIe9xhUdxYIQpnLCiDjM5R/zX6JF/7zpNvwkAKI/l9uXA/0z3zSrPGa
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore
build:
  project: src\SyncService.Installer\SyncService.Installer.wixproj
  verbosity: minimal
after_build:
  # For once the build has completed
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off